# Generated by Django 5.0.3 on 2024-03-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_craft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Craft',
        ),
    ]
