# Generated by Django 5.0.3 on 2024-03-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_delete_craft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Textiles', 'Textiles'), ('Paintings', 'Paintings'), ('Stone Craft', 'Stone Craft'), ('Accessories', 'Accessories'), ('Jewelry', 'Jewelry'), ('Handmade Crafts', 'Handmade Crafts'), ('Leather Work', 'Leather Work'), ('Pottery and Ceramics', 'Pottery and Ceramics'), ('Metalwork', 'Metalwork'), ('Others', 'Others')], default='Pottery', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='craft_images/')),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal')], default='AP', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
