# Generated by Django 5.0.3 on 2024-03-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='userapp.order'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
