# Generated by Django 5.0.3 on 2024-03-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_cartitem_order_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
