# Generated by Django 5.0.3 on 2024-03-25 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_cart_cartitem_order_orderitem_order_crafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
    ]
