# Generated by Django 5.0.3 on 2024-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='admin_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
