# Generated by Django 5.0.3 on 2024-03-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_craft_admin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('additional_comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
