# Generated by Django 5.0.3 on 2024-04-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_user_aadhar_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='craft_videos/'),
        ),
    ]
