# Generated by Django 5.0.3 on 2024-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_craft_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
