# Generated by Django 5.0.3 on 2024-04-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_craft_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='delivery_status',
        ),
    ]
