# Generated by Django 3.2.25 on 2025-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_remove_craft_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='craft',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Books', 'Books'), ('Toys', 'Toys'), ('Automobiles', 'Automobiles'), ('Sports Equipment', 'Sports Equipment'), ('Others', 'Others')], default='Pottery', max_length=50),
        ),
    ]
