# Generated by Django 5.0.3 on 2025-03-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_auto_20250303_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_to_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
