# Generated by Django 5.0.3 on 2025-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_user_allow_to_sell_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
