# Generated by Django 5.0.6 on 2025-03-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_craft_brand_name_craft_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
