# Generated by Django 4.2.7 on 2025-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_aadhaardetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaardetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaardetail',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaardetail',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
