# Generated by Django 4.2.7 on 2025-03-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_alter_aadhaardetail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardetail',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
