# Generated by Django 5.0.3 on 2025-03-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_alter_aadhaardetail_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_fingerprint',
            field=models.ImageField(blank=True, null=True, upload_to='images/fingerprints'),
        ),
    ]
